DROP DATABASE IF EXISTS g0qqfiodiu67f1dc;
CREATE DATABASE g0qqfiodiu67f1dc;
USE g0qqfiodiu67f1dc;


CREATE TABLE Burgers (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	devoured TINYINT(1) DEFAULT '0',
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

